service: social-networking-serverless-kata

frameworkVersion: "2"

provider:
    apiGateway:
        shouldStartNameWithService: true
    name: aws
    region: eu-central-1
    runtime: nodejs14.x
    lambdaHashingVersion: 20201221

# conflict with dotenv package: keep undeclared
# useDotenv: true

functions:
    app:
        handler: handler.app
        events:
            - http:
                  path: /
                  method: ANY
            - http:
                  path: posts/
                  method: get
                  request:
                      parameters:
                          querystrings:
                              username: true
            - http:
                  path: posts/
                  method: post
            - http:
                  path: posts/{id}/
                  method: delete
